version: "3"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./myapp:/myapp
    ports:
      - "81:80"
      - "8001:8000"
      - "5001:5000"
      - "3001:3000"
    command: /bin/bash
    tty: true
    stdin_open: true

